#!/bin/bash
# $Id: nextpic,v 1.12 2017/11/23 19:29:31 fulford Exp $
# $Source: /src/admin/usr/local/etc/RCS/nextpic,v $
# $Revision: 1.12 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: nextpic,v 1.12 2017/11/23 19:29:31 fulford Exp $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-v] [#]|-V"
tmp=/tmp/nextpic$$
dir="/u/fulford/cwf/pics"
hist=1
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.12 $ $Date: 2017/11/23 19:29:31 $"|			awk '{print $1,$3,$6}';exit;;  
		[1-3]) hist=$1;shift;;
	esac
done

last=`
find $dir -type f -name \*|
awk -F/ '{print $NF}'|
egrep "^[0-9]{7}\.(jpg|xcf|png|tif)"|
sed -ne "s/\(^[0-9]*\)\.[a-z]*$/\1/p"|
sort -n|
awk 'END{printf("%07u",$1)}'`
next=`expr $last + 1`

show=`expr $last - $hist`
while [ $show -le $last ];do
	if [ $verbose ];then
		showf=`printf "%07i\n" $show`
		find $dir -name $showf.???|grep -v xcf >>$tmp
	fi
	show=`expr $show + 1`
done
if [ $verbose ] ;then 
	images=`tr '\n' ' ' <$tmp`
	printf "next = %07i\n" $next
	echo History
	cat $tmp
	xv $images&
else
	printf "%07i\n" $next
fi
[ -f $tmp ] && rm $tmp
